server:
  port: 8056
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrl: http://${eureka.hostname}:${server.port}/analysis
    healthCheckUrl: http://${eureka.hostname}:${server.port}/analysis
    homePageUrl: http://${eureka.hostname}:${server.port}/analysis
    metadata-map:
      type: "LOC"
      location: "local"
      accuracy: "1.0"
      cost: "0.7"
      time: "0.1"
      id: "LOC"
      idkey: "LOC"
      iddescr: "LOC"
      urlanalysis: "/gps"
  client:
    serviceUrl:
      #defaultZone: http://e04-laptop21.et.hs-osnabrueck.de:8761/eureka/
      defaultZone: http://127.0.0.1:8050/eureka/
spring:
  application:
    name: gps-service
