eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8020/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrl: http://${eureka.hostname}:${server.port}/analysis
    healthCheckUrl: http://${eureka.hostname}:${server.port}/analysis
    homePageUrl: http://${eureka.hostname}:${server.port}/analysis
    metadata-map:
      type: "CELL"
      location: "cloud"
      accuracy: "0.9"
      cost: "0.3"
      time: "0.1"
      id: "CELL"
      urlanalysis: "/gps"
spring:
  application:
    name: gps-service

---
spring:
  profiles: cell1
server:
  port: 8028
eureka:
  instance:
    metadata-map:
      type: "CELL"
      location: "cloud"
      accuracy: "0.9"
      cost: "0.3"
      time: "0.1"
      id: "CELL"
      urlanalysis: "/gps"
