eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8020/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrl: http://${eureka.hostname}:${server.port}/analysis
    healthCheckUrl: http://${eureka.hostname}:${server.port}/analysis
    homePageUrl: http://${eureka.hostname}:${server.port}/analysis
    metadata-map:
      type: "CELLULAR"
      location: "cloud"
      accuracy: "0.7"
      cost: "0.1"
      time: "0.1"
      urlanalysis: "/gps"
spring:
  application:
    name: gps-service

---
spring:
  profiles: ogcs1
server:
  port: 8028
eureka:
  instance:
    metadata-map:
      type: "CELLULAR"
      location: "cloud"
      accuracy: "0.7"
      cost: "0.1"
      time: "0.1"
      urlanalysis: "/gps"

---
spring:
  profiles: ogcs2
server:
  port: 8029
eureka:
  instance:
    metadata-map:
      type: "CELLULAR"
      location: "cloud"
      accuracy: "0.5"
      cost: "0.1"
      time: "0.1"
      urlanalysis: "/gps"
