server:
  port: 8036
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8030/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrl: http://${eureka.hostname}:${server.port}/status
    healthCheckUrl: http://${eureka.hostname}:${server.port}/status
    homePageUrl: http://${eureka.hostname}:${server.port}/status
    metadata-map:
      type: "backup"
      location: "local"
      urlstatus: "/status"
spring:
  application:
    name: mgmt-service
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: demo
    filter:
      create: All tasks